### ISSUE TITLE
Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by nehahande07** [judero01col/Captcha-Solver#1]
@judero01col   Exception has been thrown by the target of an invocation.
Getting the inner exception as- 
Failed to find library "liblept172.dll" for platform x64. This is how it looks in my Visual studio 2017. Please suggest- Your help is extremely appreciated-
![image](https://user-images.githubusercontent.com/65600187/82415993-fc7c5500-9a96-11ea-9137-1c0e1f549a19.png)

**Comment by judero01col** [comment]
Missing libraries are added to the project.

x86/liblept172.dll
x86/libtesseract304.dll
x64/liblept172.dll
x64/libtesseract304.dll

**Comment by nehahande07** [comment]
Thanks a lot @judero01col . It is working now. Thank you so much for the quick reply and support.

**Comment by judero01col** [comment]
You're welcome, if you have any problem don't hesitate to ask.
